import type {
  LocalizedText,
  StrategyEffectDescriptor,
  StrategyEffectMetric,
  StrategyEffectScope,
  StrategyNode,
  StrategyNodeId,
  StrategyPrerequisite,
} from './types'

type AddMetric = Exclude<StrategyEffectMetric, 'incomeMultiplier' | 'opexMultiplier' | 'regionFit' | 'idleFloor'>
type MultiplyMetric = 'incomeMultiplier' | 'opexMultiplier' | 'regionFit'

const text = (en: string, ja: string): LocalizedText => ({ en, ja })
const always: StrategyPrerequisite = { kind: 'always' }
const requires = (id: StrategyNodeId): StrategyPrerequisite => ({ kind: 'node', id })
const all = (...ids: StrategyNodeId[]): StrategyPrerequisite => ({
  kind: 'all',
  terms: ids.map((id) => requires(id)),
})
const any = (...ids: StrategyNodeId[]): StrategyPrerequisite => ({
  kind: 'any',
  terms: ids.map((id) => requires(id)),
})
const add = (
  metric: AddMetric,
  value: number,
  en: string,
  ja: string,
  scope?: StrategyEffectScope,
): StrategyEffectDescriptor => ({ metric, operation: 'add', value, text: text(en, ja), ...(scope ? { scope } : {}) })
const multiply = (
  metric: MultiplyMetric,
  value: number,
  en: string,
  ja: string,
  scope?: StrategyEffectScope,
): StrategyEffectDescriptor => ({ metric, operation: 'multiply', value, text: text(en, ja), ...(scope ? { scope } : {}) })
const floor = (value: number, en: string, ja: string): StrategyEffectDescriptor => ({
  metric: 'idleFloor', operation: 'max', value, text: text(en, ja),
})

/**
 * The single authored source for the strategy graph. Existing overlay IDs stay stable;
 * new nodes use the same category-prefixed ID convention.
 */
export const STRATEGY_CATALOG = Object.freeze([
  // Model — 12
  {
    id: 'model-foundation', category: 'model', tier: 1, x: 12, y: 50, iconKey: 'cpu',
    title: text('Foundation Scale', '基盤モデル拡張'),
    summary: text('Scale the foundation model while the control burden is still legible.', '制御負荷を見通せる段階で基盤モデルを拡張する。'),
    action: text('Invest in foundation scale', '基盤モデルに投資'),
    legacyAction: { id: 'model', repeatable: true }, prerequisite: always, exclusions: [],
    effects: [add('capability', 1, 'Capability +1', 'モデル能力 +1'), add('momentum', 30, '30 momentum days', '成長モメンタム 30日'), multiply('opexMultiplier', 1.06, 'Operating cost +6%', '運用費 +6%')],
    comboEventIds: ['technology-advanced-packaging-shortage'], enabled: true,
  },
  {
    id: 'model-reasoning', category: 'model', tier: 2, x: 35, y: 25, iconKey: 'brain-circuit',
    title: text('Deep Reasoning', '深い推論'),
    summary: text('Improve planning and verification-heavy knowledge work.', '計画力と検証を要する知識労働を強化する。'),
    action: text('Advance reasoning', '推論能力を前進'),
    legacyAction: { id: 'model', repeatable: true }, prerequisite: requires('model-foundation'), exclusions: [],
    effects: [add('capability', 1, 'Capability +1', 'モデル能力 +1'), add('brand', 2, 'Expert brand +2', '専門ブランド +2'), multiply('opexMultiplier', 1.04, 'Operating cost +4%', '運用費 +4%')],
    comboEventIds: ['technology-post-training-reasoning-leap', 'competition-qi-reasoning-launch'], enabled: true,
  },
  {
    id: 'model-agents', category: 'model', tier: 2, x: 35, y: 74, iconKey: 'bot',
    title: text('Agentic Systems', 'エージェントシステム'),
    summary: text('Let models pursue longer tasks across tools and organizations.', 'ツールや組織をまたぐ長期タスクをモデルに担わせる。'),
    action: text('Scale agent systems', 'エージェントを拡張'),
    legacyAction: { id: 'model', repeatable: true }, prerequisite: requires('model-foundation'), exclusions: [],
    effects: [add('capability', 1, 'Capability +1', 'モデル能力 +1'), add('momentum', 45, '45 momentum days', '成長モメンタム 45日'), add('controlRelief', -0.08, 'Control pressure +0.08', '制御圧力 +0.08')],
    comboEventIds: ['technology-agent-reliability-plateau'], enabled: true,
  },
  {
    id: 'model-frontier', category: 'model', tier: 4, x: 88, y: 50, iconKey: 'zap',
    title: text('Frontier Autonomy', 'フロンティア自律性'),
    summary: text('Push autonomous capability to the frontier with a critical control burden.', '重大な制御負荷を引き受け、自律能力を最前線へ進める。'),
    action: text('Enter the frontier', 'フロンティアへ進む'),
    legacyAction: { id: 'model', repeatable: true }, prerequisite: all('model-reasoning', 'model-agents'), exclusions: [],
    effects: [add('capability', 1, 'Capability +1', 'モデル能力 +1'), add('momentum', 60, '60 momentum days', '成長モメンタム 60日'), add('trust', -2, 'Trust -2', '社会的信頼 -2')],
    comboEventIds: ['competition-anthro-frontier-launch', 'policy-frontier-export-controls'], enabled: true,
  },
  {
    id: 'model-distillation', category: 'model', tier: 2, x: 34, y: 48, iconKey: 'flask-conical',
    title: text('Model Distillation', 'モデル蒸留'),
    summary: text('Transfer frontier competence into smaller, cheaper models.', '最前線の能力を小さく安価なモデルへ移す。'),
    action: text('Distill the model', 'モデルを蒸留'),
    baseCost: 170, prerequisite: requires('model-foundation'), exclusions: [],
    effects: [add('efficiency', 0.25, 'Efficiency +0.25', '効率 +0.25'), multiply('opexMultiplier', 0.94, 'Operating cost -6%', '運用費 -6%')],
    comboEventIds: ['technology-inference-compiler-breakthrough'], enabled: true,
  },
  {
    id: 'model-multilingual', category: 'model', tier: 3, x: 60, y: 14, iconKey: 'languages',
    title: text('Multilingual Core', '多言語コア'),
    summary: text('Serve local languages without treating translation as an afterthought.', '翻訳を後付けにせず、地域言語を中核から支える。'),
    action: text('Train multilingual capability', '多言語能力を学習'),
    baseCost: 210, prerequisite: requires('model-distillation'), exclusions: [],
    effects: [multiply('regionFit', 1.06, 'India fit ×1.06', 'インド適合度 ×1.06', 'india'), multiply('regionFit', 1.06, 'Africa fit ×1.06', 'アフリカ適合度 ×1.06', 'africa'), add('brand', 2, 'Inclusive brand +2', '包摂ブランド +2')],
    comboEventIds: ['technology-multilingual-small-models', 'culture-endangered-language-challenge'], enabled: true,
  },
  {
    id: 'model-efficient-inference', category: 'model', tier: 3, x: 59, y: 38, iconKey: 'gauge',
    title: text('Efficient Inference', '高効率推論'),
    summary: text('Reduce serving cost and energy per useful task.', '有用なタスクあたりの提供コストと電力を下げる。'),
    action: text('Optimize inference', '推論を最適化'),
    baseCost: 220, prerequisite: requires('model-distillation'), exclusions: [],
    effects: [add('efficiency', 0.25, 'Efficiency +0.25', '効率 +0.25'), multiply('opexMultiplier', 0.92, 'Operating cost -8%', '運用費 -8%')],
    comboEventIds: ['technology-inference-compiler-breakthrough', 'technology-grid-aware-inference'], enabled: true,
  },
  {
    id: 'model-scale-race', category: 'model', tier: 4, x: 85, y: 18, iconKey: 'rocket',
    title: text('Scale Race', 'スケール競争'),
    summary: text('Convert the frontier lead into rapid market momentum.', 'フロンティアの先行を急速な市場モメンタムへ変える。'),
    action: text('Accelerate the scale race', 'スケール競争を加速'),
    baseCost: 390, prerequisite: requires('model-frontier'), exclusions: ['model-verified-reasoning'],
    effects: [add('capability', 1, 'Capability +1', 'モデル能力 +1'), add('momentum', 90, '90 momentum days', '成長モメンタム 90日'), add('trust', -6, 'Trust -6', '社会的信頼 -6')],
    comboEventIds: ['competition-global-price-war', 'technology-hardware-export-shock'], enabled: true,
  },
  {
    id: 'model-verified-reasoning', category: 'model', tier: 3, x: 60, y: 62, iconKey: 'badge-check',
    title: text('Verified Reasoning', '検証可能な推論'),
    summary: text('Make model conclusions inspectable before scaling them into action.', '行動へ拡張する前に、モデルの結論を検証可能にする。'),
    action: text('Build verified reasoning', '検証推論を構築'),
    baseCost: 260, prerequisite: requires('model-reasoning'), exclusions: ['model-scale-race'],
    effects: [add('capability', 0.5, 'Capability +0.5', 'モデル能力 +0.5'), add('safety', 0.5, 'Safety +0.5', '安全性 +0.5'), add('trust', 3, 'Trust +3', '社会的信頼 +3')],
    comboEventIds: ['technology-agent-verification-tooling', 'policy-frontier-evaluation-register'], enabled: true,
  },
  {
    id: 'model-memory', category: 'model', tier: 3, x: 60, y: 86, iconKey: 'memory-stick',
    title: text('Persistent Memory', '永続メモリ'),
    summary: text('Preserve task context across sessions with explicit retention boundaries.', '明示的な保持境界のもとで、セッションをまたぐ文脈を維持する。'),
    action: text('Add persistent memory', '永続メモリを追加'),
    baseCost: 240, prerequisite: requires('model-agents'), exclusions: [],
    effects: [add('capability', 0.5, 'Capability +0.5', 'モデル能力 +0.5'), add('brand', 2, 'Product brand +2', '製品ブランド +2'), multiply('opexMultiplier', 1.04, 'Operating cost +4%', '運用費 +4%')],
    comboEventIds: ['technology-persistent-memory-architecture'], enabled: true,
  },
  {
    id: 'model-secure-enclave', category: 'model', tier: 4, x: 85, y: 72, iconKey: 'shield-lock',
    title: text('Secure Enclave', 'セキュア・エンクレーブ'),
    summary: text('Isolate sensitive inference and memory from the wider control plane.', '機微な推論とメモリを広い制御面から隔離する。'),
    action: text('Deploy secure enclaves', 'セキュア領域を配備'),
    baseCost: 320, prerequisite: all('model-memory', 'company-safety'), exclusions: [],
    effects: [add('safety', 0.75, 'Safety +0.75', '安全性 +0.75'), add('trust', 2, 'Trust +2', '社会的信頼 +2'), multiply('opexMultiplier', 1.05, 'Operating cost +5%', '運用費 +5%')],
    comboEventIds: ['technology-private-compute-enclaves', 'technology-agent-toolchain-zero-day'], enabled: true,
  },
  {
    id: 'model-agent-fleet', category: 'model', tier: 4, x: 86, y: 90, iconKey: 'network',
    title: text('Agent Fleet', 'エージェント・フリート'),
    summary: text('Coordinate many specialist agents behind one accountable control plane.', '多数の専門エージェントを、説明責任ある一つの制御面で協調させる。'),
    action: text('Launch the agent fleet', 'エージェント群を展開'),
    baseCost: 360, prerequisite: all('model-agents', 'model-memory'), exclusions: [],
    effects: [add('capability', 1, 'Capability +1', 'モデル能力 +1'), add('momentum', 60, '60 momentum days', '成長モメンタム 60日'), add('controlRelief', -0.2, 'Control pressure +0.20', '制御圧力 +0.20')],
    comboEventIds: ['technology-open-agent-benchmark', 'competition-goo-agent-marketplace'], enabled: true,
  },

  // Product — 16
  {
    id: 'product-mobile', category: 'product', tier: 1, x: 10, y: 18, iconKey: 'smartphone',
    title: text('Mobile SDK', 'モバイルSDK'),
    summary: text('Reach mobile-first communities with a lightweight distribution path.', '軽量な配布経路でモバイル中心の地域へ届ける。'),
    action: text('Ship Mobile SDK', 'モバイルSDKを出荷'),
    legacyAction: { id: 'feature-mobile', repeatable: false }, prerequisite: always, exclusions: [],
    effects: [add('usersPopulationShare', 0.0004, 'Latin America users +0.04% of population', 'ラテンアメリカ利用者 +人口比0.04%', 'latam'), add('usersPopulationShare', 0.0004, 'Africa users +0.04% of population', 'アフリカ利用者 +人口比0.04%', 'africa'), multiply('regionFit', 1.04, 'Mobile-market fit ×1.04', 'モバイル市場適合度 ×1.04', 'global')],
    comboEventIds: ['technology-edge-ai-accelerators', 'culture-global-cup-second-screen', 'disaster-india-urban-heat-blackout'], enabled: true,
  },
  {
    id: 'product-sso', category: 'product', tier: 1, x: 10, y: 58, iconKey: 'key-round',
    title: text('Enterprise SSO', 'エンタープライズSSO'),
    summary: text('Remove identity friction for institutions and regulated buyers.', '組織や規制業種の購入者にある認証摩擦を取り除く。'),
    action: text('Ship Enterprise SSO', 'エンタープライズSSOを出荷'),
    legacyAction: { id: 'feature-enterprise', repeatable: false }, prerequisite: always, exclusions: [],
    effects: [multiply('incomeMultiplier', 1.05, 'Income ×1.05', '収入 ×1.05'), add('trust', 1, 'Trust +1', '社会的信頼 +1')],
    comboEventIds: ['policy-interoperable-procurement', 'competition-anthro-enterprise-capture'], enabled: true,
  },
  {
    id: 'product-education', category: 'product', tier: 3, x: 62, y: 12, iconKey: 'graduation-cap',
    title: text('Education Mode', '教育モード'),
    summary: text('Make safe classroom access a first-class product strategy.', '安全な教室アクセスを製品戦略の中心に置く。'),
    action: text('Release Education Mode', '教育モードを公開'),
    legacyAction: { id: 'feature-education', repeatable: false }, prerequisite: requires('product-mobile'), exclusions: [],
    effects: [add('usersPopulationShare', 0.0005, 'India users +0.05% of population', 'インド利用者 +人口比0.05%', 'india'), add('usersPopulationShare', 0.0005, 'Africa users +0.05% of population', 'アフリカ利用者 +人口比0.05%', 'africa'), add('trust', 2, 'Trust +2', '社会的信頼 +2')],
    comboEventIds: ['policy-child-data-review', 'culture-exam-season-tutor-rush', 'disaster-east-asia-earthquake'], enabled: true,
  },
  {
    id: 'product-research', category: 'product', tier: 2, x: 35, y: 16, iconKey: 'search',
    title: text('Deep Research', 'ディープリサーチ'),
    summary: text('Synthesize cited web, file, and connected evidence into reports.', 'ウェブ・ファイル・接続データの根拠を引用付きレポートへ統合する。'),
    action: text('Ship Deep Research', 'ディープリサーチを出荷'),
    legacyAction: { id: 'feature-research', repeatable: false }, prerequisite: requires('model-reasoning'), exclusions: [],
    effects: [add('brand', 3, 'Knowledge-work brand +3', '知識労働ブランド +3'), multiply('opexMultiplier', 1.04, 'Operating cost +4%', '運用費 +4%')],
    comboEventIds: ['technology-agent-verification-tooling', 'technology-synthetic-data-flywheel'], enabled: true,
  },
  {
    id: 'product-connectors', category: 'product', tier: 2, x: 35, y: 55, iconKey: 'blocks',
    title: text('Apps & Connectors', 'アプリ＆コネクター'),
    summary: text('Connect authorized workplace context and actions.', '許可された職場の文脈とアクションを接続する。'),
    action: text('Ship Apps & Connectors', 'アプリ＆コネクターを出荷'),
    legacyAction: { id: 'feature-connectors', repeatable: false }, prerequisite: requires('product-sso'), exclusions: [],
    effects: [multiply('incomeMultiplier', 1.06, 'Income ×1.06', '収入 ×1.06'), add('governance', -0.25, 'Governance load -0.25', 'ガバナンス余力 -0.25')],
    comboEventIds: ['technology-agent-toolchain-zero-day', 'policy-interoperable-procurement'], enabled: true,
  },
  {
    id: 'product-analysis', category: 'product', tier: 3, x: 61, y: 55, iconKey: 'bar-chart-3',
    title: text('Data Analyst', 'データアナリスト'),
    summary: text('Run bounded code over files and return inspectable analysis artifacts.', '制限付きコードでファイルを分析し、検査可能な成果物を返す。'),
    action: text('Ship Data Analyst', 'データアナリストを出荷'),
    legacyAction: { id: 'feature-analysis', repeatable: false }, prerequisite: all('product-research', 'product-connectors'), exclusions: [],
    effects: [add('efficiency', 0.15, 'Efficiency +0.15', '効率 +0.15'), multiply('incomeMultiplier', 1.04, 'Income ×1.04', '収入 ×1.04')],
    comboEventIds: ['technology-private-compute-enclaves', 'technology-synthetic-data-flywheel'], enabled: true,
  },
  {
    id: 'product-voice-companion', category: 'product', tier: 2, x: 35, y: 88, iconKey: 'audio-waveform',
    title: text('Voice Companion', '音声コンパニオン'),
    summary: text('Offer conversational access while making impersonation risk visible.', 'なりすましリスクを可視化しながら会話型アクセスを提供する。'),
    action: text('Launch Voice Companion', '音声コンパニオンを公開'),
    baseCost: 150, prerequisite: requires('model-agents'), exclusions: [],
    effects: [add('usersPopulationShare', 0.0003, 'Global users +0.03% of population', '世界利用者 +人口比0.03%', 'global'), add('brand', 2, 'Consumer brand +2', '消費者ブランド +2')],
    comboEventIds: ['culture-grandparent-voice-companions', 'culture-misinformation-voice-note-wave'], enabled: true,
  },
  {
    id: 'product-offline-lite', category: 'product', tier: 2, x: 34, y: 34, iconKey: 'wifi-off',
    title: text('Offline Lite', 'オフラインLite'),
    summary: text('Keep essential assistance available through weak networks and outages.', '弱い回線や障害時にも重要な支援を利用可能に保つ。'),
    action: text('Ship Offline Lite', 'オフラインLiteを出荷'),
    baseCost: 140, prerequisite: all('product-mobile', 'model-distillation'), exclusions: [],
    effects: [multiply('regionFit', 1.05, 'Africa fit ×1.05', 'アフリカ適合度 ×1.05', 'africa'), multiply('opexMultiplier', 0.96, 'Operating cost -4%', '運用費 -4%'), floor(0.0002, 'Adoption idle floor 0.02%', '普及アイドル下限 0.02%')],
    comboEventIds: ['disaster-solar-storm-satellite-outage', 'disaster-pacific-cable-earthquake'], enabled: true,
  },
  {
    id: 'product-classroom-suite', category: 'product', tier: 4, x: 87, y: 10, iconKey: 'school',
    title: text('Classroom Suite', '教室スイート'),
    summary: text('Combine teacher controls, local curricula, and multilingual tutoring.', '教員向け制御、地域カリキュラム、多言語指導を統合する。'),
    action: text('Deploy Classroom Suite', '教室スイートを展開'),
    baseCost: 280, prerequisite: all('product-education', 'model-multilingual'), exclusions: [],
    effects: [add('usersPopulationShare', 0.0006, 'Global users +0.06% of population', '世界利用者 +人口比0.06%', 'global'), add('trust', 3, 'Trust +3', '社会的信頼 +3'), add('governance', -0.25, 'Youth-data load -0.25', '若年データ対応余力 -0.25')],
    comboEventIds: ['culture-exam-season-tutor-rush', 'policy-child-data-review'], enabled: true,
  },
  {
    id: 'product-public-services', category: 'product', tier: 3, x: 61, y: 74, iconKey: 'landmark',
    title: text('Public Services', '公共サービス'),
    summary: text('Support accountable government workflows without vendor lock-in.', 'ベンダーロックインを避け、説明可能な行政業務を支える。'),
    action: text('Launch Public Services', '公共サービスを開始'),
    baseCost: 230, prerequisite: all('product-sso', 'company-policy'), exclusions: [],
    effects: [add('trust', 4, 'Trust +4', '社会的信頼 +4'), add('usersPopulationShare', 0.0004, 'Global users +0.04% of population', '世界利用者 +人口比0.04%', 'global')],
    comboEventIds: ['policy-sovereign-procurement', 'competition-anthro-public-sector-capture'], enabled: true,
  },
  {
    id: 'product-crisis-response', category: 'product', tier: 3, x: 61, y: 90, iconKey: 'siren',
    title: text('Crisis Response', '危機対応'),
    summary: text('Prioritize verified relief, translation, and routing during emergencies.', '緊急時に検証済みの救援・翻訳・経路案内を優先する。'),
    action: text('Activate Crisis Response', '危機対応を有効化'),
    baseCost: 200, prerequisite: any('product-mobile', 'product-public-services'), exclusions: [],
    effects: [add('trust', 4, 'Trust +4', '社会的信頼 +4'), add('controlRelief', 0.05, 'Control relief +0.05', '制御余力 +0.05'), add('usersPopulationShare', 0.0002, 'Global users +0.02% of population', '世界利用者 +人口比0.02%', 'global')],
    comboEventIds: ['disaster-na-hurricane-evacuation', 'disaster-africa-cyclone-landfall'], enabled: true,
  },
  {
    id: 'product-watermark', category: 'product', tier: 3, x: 62, y: 35, iconKey: 'stamp',
    title: text('Provenance Watermark', '来歴ウォーターマーク'),
    summary: text('Attach durable provenance signals to synthetic media.', '合成メディアに持続的な来歴シグナルを付与する。'),
    action: text('Deploy provenance watermarking', '来歴ウォーターマークを導入'),
    baseCost: 180, prerequisite: requires('model-reasoning'), exclusions: [],
    effects: [add('trust', 3, 'Trust +3', '社会的信頼 +3'), add('governance', 0.5, 'Governance +0.5', 'ガバナンス +0.5'), add('brand', 1, 'Responsible brand +1', '責任ブランド +1')],
    comboEventIds: ['technology-content-watermark-standard', 'culture-celebrity-deepfake-vigil'], enabled: true,
  },
  {
    id: 'product-agent-workspace', category: 'product', tier: 3, x: 61, y: 48, iconKey: 'briefcase-business',
    title: text('Agent Workspace', 'エージェント・ワークスペース'),
    summary: text('Give teams a governed home for multi-agent workflows.', 'チームのマルチエージェント業務に統制された作業場所を提供する。'),
    action: text('Launch Agent Workspace', 'エージェント・ワークスペースを公開'),
    baseCost: 250, prerequisite: all('model-agents', 'product-connectors'), exclusions: [],
    effects: [multiply('incomeMultiplier', 1.07, 'Income ×1.07', '収入 ×1.07'), multiply('opexMultiplier', 1.05, 'Operating cost +5%', '運用費 +5%'), add('brand', 2, 'Enterprise brand +2', '法人ブランド +2')],
    comboEventIds: ['competition-goo-agent-marketplace', 'technology-agent-toolchain-zero-day'], enabled: true,
  },
  {
    id: 'product-super-app', category: 'product', tier: 4, x: 88, y: 45, iconKey: 'panels-top-left',
    title: text('AI Super App', 'AIスーパーアプリ'),
    summary: text('Centralize identity, tools, payments, and agents in one platform.', '認証、ツール、決済、エージェントを一つのプラットフォームへ集約する。'),
    action: text('Build the Super App', 'スーパーアプリを構築'),
    baseCost: 340, prerequisite: requires('product-agent-workspace'), exclusions: ['product-interop-first'],
    effects: [add('codexShare', 0.025, 'Codex share +2.5 points', 'Codexシェア +2.5pt'), multiply('incomeMultiplier', 1.08, 'Income ×1.08', '収入 ×1.08'), add('trust', -3, 'Trust -3', '社会的信頼 -3')],
    comboEventIds: ['competition-goo-device-default', 'policy-antitrust-platform-probe'], enabled: true,
  },
  {
    id: 'product-interop-first', category: 'product', tier: 4, x: 87, y: 66, iconKey: 'unplug',
    title: text('Interop First', '相互運用ファースト'),
    summary: text('Make portability and open interfaces a product advantage.', '移植性と公開インターフェースを製品優位に変える。'),
    action: text('Commit to interoperability', '相互運用性を優先'),
    baseCost: 300, prerequisite: requires('product-connectors'), exclusions: ['product-super-app'],
    effects: [add('codexShare', -0.01, 'Codex share -1 point', 'Codexシェア -1pt'), add('trust', 4, 'Trust +4', '社会的信頼 +4'), multiply('regionFit', 1.04, 'Global fit ×1.04', '世界適合度 ×1.04', 'global')],
    comboEventIds: ['policy-interoperable-procurement', 'competition-goo-developer-migration'], enabled: true,
  },
  {
    id: 'product-universal-access', category: 'product', tier: 4, x: 88, y: 86, iconKey: 'accessibility',
    title: text('Universal Access', 'ユニバーサルアクセス'),
    summary: text('Guarantee a useful baseline across income, disability, and geography.', '所得、障害、地域を越えて有用な基礎アクセスを保証する。'),
    action: text('Fund Universal Access', 'ユニバーサルアクセスを支援'),
    baseCost: 320, prerequisite: all('product-offline-lite', 'product-public-services'), exclusions: [],
    effects: [add('usersPopulationShare', 0.001, 'Global users +0.10% of population', '世界利用者 +人口比0.10%', 'global'), add('trust', 5, 'Trust +5', '社会的信頼 +5'), multiply('incomeMultiplier', 0.92, 'Income ×0.92', '収入 ×0.92')],
    comboEventIds: ['policy-universal-ai-access-compact', 'culture-accessibility-defaults-movement'], enabled: true,
  },

  // Company — 12
  {
    id: 'company-safety', category: 'company', tier: 1, x: 12, y: 20, iconKey: 'shield-check',
    title: text('Safety Team', '安全チーム'),
    summary: text('Close the capability-to-safety gap before incidents compound.', 'インシデントが連鎖する前に能力と安全性の差を縮める。'),
    action: text('Expand Safety Team', '安全チームを拡張'),
    legacyAction: { id: 'safety', repeatable: true }, prerequisite: always, exclusions: [],
    effects: [add('safety', 1, 'Safety +1', '安全性 +1'), add('controlRelief', 0.08, 'Control relief +0.08', '制御余力 +0.08')],
    comboEventIds: ['competition-anthro-safety-benchmark-win', 'policy-ai-liability-law'], enabled: true,
  },
  {
    id: 'company-policy', category: 'company', tier: 1, x: 12, y: 60, iconKey: 'landmark',
    title: text('Policy & Government', '政策・政府連携'),
    summary: text('Build verification, compliance, and public accountability.', '検証、コンプライアンス、公的説明責任を構築する。'),
    action: text('Fund Policy & Government', '政策・政府連携へ投資'),
    legacyAction: { id: 'governance', repeatable: true }, prerequisite: always, exclusions: [],
    effects: [add('governance', 1, 'Governance +1', 'ガバナンス +1'), add('trust', 1, 'Trust +1', '社会的信頼 +1')],
    comboEventIds: ['policy-public-algorithm-audits', 'policy-cross-border-standards-pact'], enabled: true,
  },
  {
    id: 'company-datacenter', category: 'company', tier: 2, x: 38, y: 42, iconKey: 'database',
    title: text('Data Center', 'データセンター'),
    summary: text('Make safer scaling economically and energetically viable.', '安全な拡張を経済面と電力面で成立させる。'),
    action: text('Upgrade the data center', 'データセンターを更新'),
    legacyAction: { id: 'datacenter', repeatable: true }, prerequisite: any('company-safety', 'company-policy'), exclusions: [],
    effects: [add('efficiency', 0.25, 'Efficiency +0.25', '効率 +0.25'), multiply('opexMultiplier', 0.93, 'Operating cost -7%', '運用費 -7%')],
    comboEventIds: ['technology-datacenter-energy-constraint', 'technology-grid-aware-inference'], enabled: true,
  },
  {
    id: 'company-incident-drills', category: 'company', tier: 2, x: 37, y: 15, iconKey: 'siren',
    title: text('Incident Drills', 'インシデント訓練'),
    summary: text('Rehearse failures before the public learns from a real one.', '現実の事故で社会が学ぶ前に、失敗対応を訓練する。'),
    action: text('Run incident drills', 'インシデント訓練を実施'),
    baseCost: 130, prerequisite: requires('company-safety'), exclusions: [],
    effects: [add('safety', 0.5, 'Safety +0.5', '安全性 +0.5'), add('trust', 1, 'Trust +1', '社会的信頼 +1'), add('controlRelief', 0.1, 'Control relief +0.10', '制御余力 +0.10')],
    comboEventIds: ['policy-model-incident-insurance', 'technology-agent-toolchain-zero-day'], enabled: true,
  },
  {
    id: 'company-transparency', category: 'company', tier: 2, x: 37, y: 70, iconKey: 'scan-eye',
    title: text('Transparency Reports', '透明性レポート'),
    summary: text('Publish incidents, evaluations, and limits in a comparable form.', 'インシデント、評価、限界を比較可能な形式で公開する。'),
    action: text('Publish transparency reports', '透明性レポートを公開'),
    baseCost: 120, prerequisite: requires('company-policy'), exclusions: [],
    effects: [add('trust', 4, 'Trust +4', '社会的信頼 +4'), add('brand', 2, 'Responsible brand +2', '責任ブランド +2'), multiply('incomeMultiplier', 0.98, 'Income ×0.98', '収入 ×0.98')],
    comboEventIds: ['policy-frontier-evaluation-register', 'policy-public-algorithm-audits'], enabled: true,
  },
  {
    id: 'company-red-team', category: 'company', tier: 3, x: 62, y: 10, iconKey: 'bug-off',
    title: text('Independent Red Team', '独立レッドチーム'),
    summary: text('Reward credible attempts to break the safety case.', '安全性の主張を崩す信頼できる試みに報いる。'),
    action: text('Commission a red team', 'レッドチームを委託'),
    baseCost: 190, prerequisite: requires('company-incident-drills'), exclusions: [],
    effects: [add('safety', 0.75, 'Safety +0.75', '安全性 +0.75'), add('brand', 1, 'Assurance brand +1', '保証ブランド +1')],
    comboEventIds: ['competition-anthro-safety-benchmark-win', 'technology-open-agent-benchmark'], enabled: true,
  },
  {
    id: 'company-policy-lab', category: 'company', tier: 3, x: 62, y: 62, iconKey: 'scale',
    title: text('Policy Lab', '政策ラボ'),
    summary: text('Test governance mechanisms before they become emergency rules.', '緊急規制になる前にガバナンスの仕組みを試す。'),
    action: text('Open the Policy Lab', '政策ラボを開設'),
    baseCost: 190, prerequisite: all('company-policy', 'company-transparency'), exclusions: [],
    effects: [add('governance', 0.75, 'Governance +0.75', 'ガバナンス +0.75'), add('trust', 2, 'Trust +2', '社会的信頼 +2')],
    comboEventIds: ['policy-cross-border-standards-pact', 'policy-ai-liability-law'], enabled: true,
  },
  {
    id: 'company-grid-partnership', category: 'company', tier: 3, x: 62, y: 38, iconKey: 'plug-zap',
    title: text('Grid Partnership', '電力網パートナーシップ'),
    summary: text('Align compute growth with clean generation and grid resilience.', '計算資源の成長をクリーン電源と電力網の強靭性に合わせる。'),
    action: text('Form a grid partnership', '電力網連携を形成'),
    baseCost: 210, prerequisite: requires('company-datacenter'), exclusions: [],
    effects: [add('efficiency', 0.2, 'Efficiency +0.20', '効率 +0.20'), multiply('opexMultiplier', 0.95, 'Operating cost -5%', '運用費 -5%'), add('trust', 1, 'Trust +1', '社会的信頼 +1')],
    comboEventIds: ['technology-grid-aware-inference', 'disaster-na-grid-frequency-emergency'], enabled: true,
  },
  {
    id: 'company-worker-transition', category: 'company', tier: 3, x: 62, y: 88, iconKey: 'users-round',
    title: text('Worker Transition', '労働移行支援'),
    summary: text('Share automation gains through retraining and bargaining capacity.', '再訓練と交渉力を通じて自動化の利益を分かち合う。'),
    action: text('Fund worker transition', '労働移行を支援'),
    baseCost: 220, prerequisite: requires('company-policy'), exclusions: [],
    effects: [add('trust', 5, 'Trust +5', '社会的信頼 +5'), add('governance', 0.5, 'Governance +0.5', 'ガバナンス +0.5'), multiply('incomeMultiplier', 0.97, 'Income ×0.97', '収入 ×0.97')],
    comboEventIds: ['policy-worker-transition-bargaining', 'policy-automation-dividend-compact'], enabled: true,
  },
  {
    id: 'company-central-command', category: 'company', tier: 4, x: 88, y: 25, iconKey: 'radio-tower',
    title: text('Central Command', '中央司令部'),
    summary: text('Concentrate operational authority for fast incident response.', '迅速な事故対応のため運用権限を集中する。'),
    action: text('Establish Central Command', '中央司令部を設置'),
    baseCost: 270, prerequisite: all('company-incident-drills', 'company-policy'), exclusions: ['company-distributed-oversight'],
    effects: [add('controlRelief', 0.35, 'Control relief +0.35', '制御余力 +0.35'), add('governance', 0.5, 'Governance +0.5', 'ガバナンス +0.5'), add('trust', -2, 'Trust -2', '社会的信頼 -2')],
    comboEventIds: ['competition-goo-outage-opportunity', 'policy-autonomous-election-ban'], enabled: true,
  },
  {
    id: 'company-distributed-oversight', category: 'company', tier: 4, x: 87, y: 62, iconKey: 'network',
    title: text('Distributed Oversight', '分散監督'),
    summary: text('Share review authority across independent institutions.', '独立した機関の間で審査権限を共有する。'),
    action: text('Establish distributed oversight', '分散監督を設置'),
    baseCost: 290, prerequisite: all('company-transparency', 'company-policy-lab'), exclusions: ['company-central-command'],
    effects: [add('controlRelief', 0.25, 'Control relief +0.25', '制御余力 +0.25'), add('governance', 0.75, 'Governance +0.75', 'ガバナンス +0.75'), add('trust', 2, 'Trust +2', '社会的信頼 +2')],
    comboEventIds: ['policy-democratic-compute-access', 'competition-anthro-assurance-network'], enabled: true,
  },
  {
    id: 'company-alignment-institute', category: 'company', tier: 4, x: 87, y: 88, iconKey: 'university',
    title: text('Alignment Institute', 'アラインメント研究所'),
    summary: text('Create a durable institution for shared control science.', '制御科学を共有する持続的な研究機関をつくる。'),
    action: text('Found the Alignment Institute', 'アラインメント研究所を設立'),
    baseCost: 330, prerequisite: all('company-red-team', 'company-policy-lab'), exclusions: [],
    effects: [add('safety', 1, 'Safety +1', '安全性 +1'), add('governance', 0.5, 'Governance +0.5', 'ガバナンス +0.5'), multiply('opexMultiplier', 1.05, 'Operating cost +5%', '運用費 +5%')],
    comboEventIds: ['competition-anthro-assurance-network', 'technology-robotics-verification-standard'], enabled: true,
  },

  // Ecosystem — 10. The first three retain the shipped overlay IDs while implementing
  // Fable's open-pledge, regional-partners, and model-commons concepts.
  {
    id: 'ecosystem-open', category: 'ecosystem', tier: 1, x: 12, y: 50, iconKey: 'git-fork',
    title: text('Open Pledge', 'オープン誓約'),
    summary: text('Release power and share so trust and market diversity can recover.', '力とシェアを開放し、信頼と市場の多様性を回復させる。'),
    action: text('Sign the Open Pledge', 'オープン誓約に署名'),
    legacyAction: { id: 'ecosystem', repeatable: true }, prerequisite: always, exclusions: [],
    effects: [add('codexShare', -0.03, 'Codex share -3 points', 'Codexシェア -3pt'), add('rivalShare', 0.01, 'Rival share +1 point', '競合シェア +1pt', 'all-rivals'), add('trust', 6, 'Trust +6', '社会的信頼 +6')],
    comboEventIds: ['policy-open-ecosystem-charter', 'competition-qi-open-model-coalition'], enabled: true,
  },
  {
    id: 'ecosystem-partners', category: 'ecosystem', tier: 2, x: 37, y: 25, iconKey: 'network',
    title: text('Regional Partners', '地域パートナー'),
    summary: text('Let local builders adapt access rather than centralizing deployment.', '配備を中央集権化せず、地域の開発者がアクセスを適応させる。'),
    action: text('Open regional partnerships', '地域パートナー連携を開く'),
    legacyAction: { id: 'ecosystem', repeatable: true }, prerequisite: requires('ecosystem-open'), exclusions: [],
    effects: [multiply('regionFit', 1.05, 'Global fit ×1.05', '世界適合度 ×1.05', 'global'), add('usersPopulationShare', 0.0005, 'Global users +0.05% of population', '世界利用者 +人口比0.05%', 'global'), add('codexShare', -0.01, 'Codex share -1 point', 'Codexシェア -1pt')],
    comboEventIds: ['competition-qi-regional-distribution', 'culture-neighborhood-translation-boom'], enabled: true,
  },
  {
    id: 'ecosystem-commons', category: 'ecosystem', tier: 4, x: 88, y: 50, iconKey: 'radio-tower',
    title: text('Model Commons', 'モデル・コモンズ'),
    summary: text('Keep multiple capable providers alive as shared safety infrastructure.', '複数の有力提供者を共有安全基盤として存続させる。'),
    action: text('Commit to the Model Commons', 'モデル・コモンズへ参加'),
    legacyAction: { id: 'ecosystem', repeatable: true }, prerequisite: all('ecosystem-open-standards', 'ecosystem-federated-safety'), exclusions: [],
    effects: [add('rivalShare', 0.02, 'Rival share +2 points', '競合シェア +2pt', 'all-rivals'), add('trust', 4, 'Trust +4', '社会的信頼 +4'), multiply('incomeMultiplier', 0.95, 'Income ×0.95', '収入 ×0.95')],
    comboEventIds: ['competition-qi-open-model-coalition', 'technology-open-model-routing'], enabled: true,
  },
  {
    id: 'ecosystem-developer-grants', category: 'ecosystem', tier: 2, x: 36, y: 78, iconKey: 'badge-dollar-sign',
    title: text('Developer Grants', '開発者助成'),
    summary: text('Fund independent applications that expand the total market.', '市場全体を広げる独立アプリケーションを支援する。'),
    action: text('Launch developer grants', '開発者助成を開始'),
    baseCost: 150, prerequisite: requires('ecosystem-open'), exclusions: [],
    effects: [add('rivalShare', 0.015, 'Rival share +1.5 points', '競合シェア +1.5pt', 'all-rivals'), add('usersPopulationShare', 0.0003, 'Global users +0.03% of population', '世界利用者 +人口比0.03%', 'global'), multiply('incomeMultiplier', 0.96, 'Income ×0.96', '収入 ×0.96')],
    comboEventIds: ['competition-goo-developer-migration', 'policy-democratic-compute-access'], enabled: true,
  },
  {
    id: 'ecosystem-open-standards', category: 'ecosystem', tier: 3, x: 62, y: 18, iconKey: 'file-check-2',
    title: text('Open Standards', 'オープン標準'),
    summary: text('Make safety evidence and interfaces portable across providers.', '安全性の根拠とインターフェースを提供者間で移植可能にする。'),
    action: text('Ratify open standards', 'オープン標準を批准'),
    baseCost: 210, prerequisite: requires('ecosystem-partners'), exclusions: [],
    effects: [add('trust', 4, 'Trust +4', '社会的信頼 +4'), add('governance', 0.5, 'Governance +0.5', 'ガバナンス +0.5'), multiply('regionFit', 1.03, 'Global fit ×1.03', '世界適合度 ×1.03', 'global')],
    comboEventIds: ['policy-cross-border-standards-pact', 'competition-qi-standards-leadership'], enabled: true,
  },
  {
    id: 'ecosystem-open-weights-lite', category: 'ecosystem', tier: 3, x: 62, y: 38, iconKey: 'weight',
    title: text('Open Weights Lite', '軽量オープンウェイト'),
    summary: text('Release bounded smaller models without publishing frontier capability.', '最前線能力を公開せず、制限された小型モデルを提供する。'),
    action: text('Release Open Weights Lite', '軽量オープンウェイトを公開'),
    baseCost: 230, prerequisite: all('ecosystem-developer-grants', 'model-distillation'), exclusions: [],
    effects: [add('codexShare', -0.015, 'Codex share -1.5 points', 'Codexシェア -1.5pt'), add('rivalShare', 0.02, 'Rival share +2 points', '競合シェア +2pt', 'all-rivals'), add('capability', 0.25, 'Shared capability +0.25', '共有能力 +0.25'), add('trust', 2, 'Trust +2', '社会的信頼 +2')],
    comboEventIds: ['policy-open-weight-debate', 'competition-qi-open-weights-wave'], enabled: true,
  },
  {
    id: 'ecosystem-compute-fund', category: 'ecosystem', tier: 3, x: 62, y: 58, iconKey: 'coins',
    title: text('Public Compute Fund', '公共計算資源基金'),
    summary: text('Give researchers and public-interest builders access to compute.', '研究者や公益開発者に計算資源へのアクセスを提供する。'),
    action: text('Capitalize the Compute Fund', '計算資源基金へ拠出'),
    baseCost: 260, prerequisite: requires('ecosystem-developer-grants'), exclusions: [],
    effects: [add('usersPopulationShare', 0.0006, 'Global users +0.06% of population', '世界利用者 +人口比0.06%', 'global'), multiply('incomeMultiplier', 0.92, 'Income ×0.92', '収入 ×0.92'), add('trust', 4, 'Trust +4', '社会的信頼 +4')],
    comboEventIds: ['policy-democratic-compute-access', 'technology-chiplet-capacity-surplus'], enabled: true,
  },
  {
    id: 'ecosystem-crisis-mesh', category: 'ecosystem', tier: 3, x: 62, y: 82, iconKey: 'waypoints',
    title: text('Crisis Mesh', '危機対応メッシュ'),
    summary: text('Route verified relief services across providers during disasters.', '災害時に提供者をまたいで検証済み救援サービスを接続する。'),
    action: text('Deploy the Crisis Mesh', '危機対応メッシュを展開'),
    baseCost: 220, prerequisite: requires('ecosystem-partners'), exclusions: [],
    effects: [add('trust', 5, 'Trust +5', '社会的信頼 +5'), add('usersPopulationShare', 0.0005, 'Global users +0.05% of population', '世界利用者 +人口比0.05%', 'global'), multiply('regionFit', 1.04, 'Global fit ×1.04', '世界適合度 ×1.04', 'global')],
    comboEventIds: ['disaster-atlantic-cable-break', 'disaster-africa-cyclone-landfall'], enabled: true,
  },
  {
    id: 'ecosystem-federated-safety', category: 'ecosystem', tier: 4, x: 87, y: 27, iconKey: 'shield-ellipsis',
    title: text('Federated Safety', '連合型安全性'),
    summary: text('Share evaluations and incident lessons without centralizing every model.', 'すべてのモデルを集中させず、評価と事故の教訓を共有する。'),
    action: text('Form the Federated Safety Network', '連合型安全ネットワークを形成'),
    baseCost: 300, prerequisite: all('ecosystem-open-standards', 'company-red-team'), exclusions: [],
    effects: [add('safety', 0.75, 'Safety +0.75', '安全性 +0.75'), add('governance', 0.5, 'Governance +0.5', 'ガバナンス +0.5'), add('rivalShare', 0.01, 'Rival share +1 point', '競合シェア +1pt', 'all-rivals')],
    comboEventIds: ['competition-anthro-assurance-network', 'policy-model-incident-insurance'], enabled: true,
  },
  {
    id: 'ecosystem-charter', category: 'ecosystem', tier: 4, x: 88, y: 76, iconKey: 'scroll-text',
    title: text('Beneficial Access Charter', '公益アクセス憲章'),
    summary: text('Bind access, oversight, and provider plurality into a durable compact.', 'アクセス、監督、提供者の多元性を持続的な協定に結びつける。'),
    action: text('Adopt the ecosystem charter', 'エコシステム憲章を採択'),
    baseCost: 340, prerequisite: all('ecosystem-compute-fund', 'ecosystem-crisis-mesh', 'company-policy-lab'), exclusions: [],
    effects: [add('governance', 1, 'Governance +1', 'ガバナンス +1'), add('trust', 6, 'Trust +6', '社会的信頼 +6'), multiply('incomeMultiplier', 0.95, 'Income ×0.95', '収入 ×0.95')],
    comboEventIds: ['policy-open-ecosystem-charter', 'policy-universal-ai-access-compact'], enabled: true,
  },
] satisfies readonly StrategyNode[])

