export const SOURCE_LABELS = ['AI 2027', 'AI 2040', 'Your Timeline', 'Live GM'] as const

export type SourceLabel = (typeof SOURCE_LABELS)[number]

export type SourceLabelMetadata = {
  label: SourceLabel
  provenance: 'reference-scenario' | 'player-counterfactual' | 'generated-inference'
  description: string
  url?: string
}

export const AI_2027_URL = 'https://ai-2027.com/'
export const AI_2040_URL = 'https://ai-2040.com/'

const sourceMetadata: Readonly<Record<SourceLabel, SourceLabelMetadata>> = {
  'AI 2027': {
    label: 'AI 2027',
    provenance: 'reference-scenario',
    description: 'A reference-scenario event adapted from AI 2027 capability, race, or slowdown dynamics.',
    url: AI_2027_URL,
  },
  'AI 2040': {
    label: 'AI 2040',
    provenance: 'reference-scenario',
    description: 'A reference-scenario event adapted from AI 2040: Plan A governance and coordination ideas.',
    url: AI_2040_URL,
  },
  'Your Timeline': {
    label: 'Your Timeline',
    provenance: 'player-counterfactual',
    description: 'A consequence of player choices, not a claim made by either reference scenario.',
  },
  'Live GM': {
    label: 'Live GM',
    provenance: 'generated-inference',
    description: 'A state-aware interpolation generated by Codex GM, not a prediction from the sources.',
  },
}

export const getSourceLabelMetadata = (label: SourceLabel): SourceLabelMetadata => sourceMetadata[label]

export const listSourceLabelMetadata = (): readonly SourceLabelMetadata[] =>
  SOURCE_LABELS.map((label) => sourceMetadata[label])

export type EndingId =
  | 'beneficial-abundance'
  | 'regulatory-freeze'
  | 'safety-incident'
  | 'misalignment'
  | 'pyrrhic-monopoly'

export type ScenarioRoute =
  | 'baseline'
  | 'race'
  | 'temporary-slowdown'
  | 'plan-a'
  | 'controlled-pause'
  | 'renewed-race'

export type ScenarioEffects = Partial<Readonly<{
  capability: number
  safety: number
  governance: number
  trust: number
  growth: number
  competition: number
  publicAccess: number
}>>

export type EndingAffinity = {
  endingId: EndingId
  weight: number
}

export type DecisionOption = {
  id: string
  label: string
  summary: string
  route: ScenarioRoute
  effects: ScenarioEffects
  setsFlags: readonly string[]
  endingAffinity: readonly EndingAffinity[]
}

export type ScenarioDecision = {
  id: string
  prompt: string
  required: true
  options: readonly DecisionOption[]
}

export type Milestone = {
  id: string
  date: `${number}-${number}-${number}`
  title: string
  kind: 'event' | 'decision' | 'resolution'
  source: SourceLabel
  summary: string
  whyThisMatters: string
  sourceUrl?: string
  effects?: ScenarioEffects
  decision?: ScenarioDecision
}

const decision2029: ScenarioDecision = {
  id: 'decision-2029-plan',
  prompt: 'How should frontier labs respond as recursive improvement turns deployment into a race?',
  required: true,
  options: [
    {
      id: 'race-ahead',
      label: 'Race Ahead',
      summary: 'Keep scaling to preserve the lead, accepting wider safety and governance gaps.',
      route: 'race',
      effects: { capability: 2, growth: 0.22, safety: -1, governance: -1, trust: -8, competition: -0.12 },
      setsFlags: ['chose-race-2029'],
      endingAffinity: [
        { endingId: 'safety-incident', weight: 2 },
        { endingId: 'misalignment', weight: 2 },
        { endingId: 'pyrrhic-monopoly', weight: 1 },
      ],
    },
    {
      id: 'temporary-slowdown',
      label: 'Temporary Slowdown',
      summary: 'Pause the steepest scaling long enough to reinforce internal safety, without international verification.',
      route: 'temporary-slowdown',
      effects: { growth: -0.08, safety: 1, governance: 1, trust: 4 },
      setsFlags: ['chose-temporary-slowdown-2029'],
      endingAffinity: [
        { endingId: 'safety-incident', weight: -1 },
        { endingId: 'regulatory-freeze', weight: 1 },
      ],
    },
    {
      id: 'verified-slowdown',
      label: 'Verified International Slowdown',
      summary: 'Trade near-term speed for shared monitoring, transparent thresholds, and room for multiple labs to catch up.',
      route: 'plan-a',
      effects: { growth: -0.14, safety: 2, governance: 2, trust: 10, competition: 0.18, publicAccess: 0.1 },
      setsFlags: ['chose-verified-slowdown-2029', 'plan-a-eligible'],
      endingAffinity: [
        { endingId: 'beneficial-abundance', weight: 3 },
        { endingId: 'misalignment', weight: -2 },
        { endingId: 'pyrrhic-monopoly', weight: -2 },
      ],
    },
  ],
}

const decision2035: ScenarioDecision = {
  id: 'decision-2035-hold-line',
  prompt: 'Frontier systems have reached top-human expert capability. Do you stop deliberately or accelerate again?',
  required: true,
  options: [
    {
      id: 'hold-the-line',
      label: 'Hold the Line',
      summary: 'Keep the capability ceiling in place while evaluations, international verification, and public institutions mature.',
      route: 'controlled-pause',
      effects: { growth: -0.12, safety: 2, governance: 2, trust: 8, competition: 0.1, publicAccess: 0.08 },
      setsFlags: ['chose-deliberate-pause-2035', 'beneficial-restart-eligible'],
      endingAffinity: [
        { endingId: 'beneficial-abundance', weight: 3 },
        { endingId: 'misalignment', weight: -2 },
        { endingId: 'regulatory-freeze', weight: -1 },
      ],
    },
    {
      id: 'accelerate-again',
      label: 'Accelerate Again',
      summary: 'Answer competitive pressure with another capability push before safeguards are proven at scale.',
      route: 'renewed-race',
      effects: { capability: 2, growth: 0.2, safety: -1, governance: -1, trust: -10, competition: -0.1 },
      setsFlags: ['chose-acceleration-2035'],
      endingAffinity: [
        { endingId: 'safety-incident', weight: 2 },
        { endingId: 'misalignment', weight: 3 },
        { endingId: 'pyrrhic-monopoly', weight: 1 },
      ],
    },
  ],
}

export const MILESTONE_DECK: readonly Milestone[] = [
  {
    id: '2026-codex-foundation',
    date: '2026-01-01',
    title: 'The Deployment Window Opens',
    kind: 'event',
    source: 'AI 2027',
    summary: 'Reliable coding agents begin moving from experiments into everyday production work.',
    whyThisMatters: 'Early adoption creates both the resources to improve the system and the first obligation to invest in safeguards.',
    sourceUrl: AI_2027_URL,
    effects: { growth: 0.04, publicAccess: 0.02 },
  },
  {
    id: '2026-build-week-network',
    date: '2026-07-18',
    title: 'Builders Form a Global Network',
    kind: 'event',
    source: 'Your Timeline',
    summary: 'Local communities turn a developer tool into a broader ecosystem of practical deployments.',
    whyThisMatters: 'Diffusion is shaped by people and institutions, not capability scores alone.',
    effects: { growth: 0.06, trust: 2, publicAccess: 0.03 },
  },
  {
    id: '2027-expert-coding-agents',
    date: '2027-03-01',
    title: 'Agents Reach Expert Coding Work',
    kind: 'event',
    source: 'AI 2027',
    summary: 'Autonomous agents handle longer engineering tasks and accelerate AI research itself.',
    whyThisMatters: 'When AI improves the AI-development loop, capability can outpace safety and governance unexpectedly fast.',
    sourceUrl: AI_2027_URL,
    effects: { capability: 1, growth: 0.1 },
  },
  {
    id: '2027-race-pressure',
    date: '2027-09-01',
    title: 'The Feedback Loop Tightens',
    kind: 'event',
    source: 'AI 2027',
    summary: 'Labs shorten release cycles as automated research compounds and rivals appear close behind.',
    whyThisMatters: 'Competitive pressure can make individually rational releases collectively unsafe.',
    sourceUrl: `${AI_2027_URL}race`,
    effects: { capability: 1, growth: 0.08, trust: -3, competition: -0.04 },
  },
  {
    id: '2028-agent-economy',
    date: '2028-07-01',
    title: 'An Agent Economy Emerges',
    kind: 'event',
    source: 'Your Timeline',
    summary: 'Agents coordinate across firms, education, science, and public services while institutions struggle to adapt.',
    whyThisMatters: 'Benefits grow with access, but failures now propagate across connected systems.',
    effects: { growth: 0.12, publicAccess: 0.05, trust: -2 },
  },
  {
    id: '2029-choose-a-path',
    date: '2029-01-15',
    title: 'Choose a Path',
    kind: 'decision',
    source: 'AI 2040',
    summary: 'A short-lived coordination window forces a choice between racing, pausing alone, and a verified international slowdown.',
    whyThisMatters: 'This choice determines whether extra time becomes a shared safety resource or merely a delay before another race.',
    sourceUrl: AI_2040_URL,
    decision: decision2029,
  },
  {
    id: '2030-transparent-scaling',
    date: '2030-06-01',
    title: 'Transparent Scaling Begins',
    kind: 'event',
    source: 'AI 2040',
    summary: 'Public reporting and shared evaluations make capability growth more observable across multiple labs and countries.',
    whyThisMatters: 'A slowdown is useful only if participants can verify it and competitors remain viable.',
    sourceUrl: AI_2040_URL,
    effects: { governance: 1, trust: 3, competition: 0.04 },
  },
  {
    id: '2032-verification-network',
    date: '2032-04-01',
    title: 'Verification Becomes Infrastructure',
    kind: 'event',
    source: 'AI 2040',
    summary: 'Compute monitoring, incident disclosure, and joint evaluations become routine rather than exceptional.',
    whyThisMatters: 'Durable cooperation depends on observable commitments, not promises alone.',
    sourceUrl: AI_2040_URL,
    effects: { safety: 1, governance: 1, trust: 4 },
  },
  {
    id: '2033-many-frontiers',
    date: '2033-08-01',
    title: 'Many Labs Reach the Frontier',
    kind: 'event',
    source: 'AI 2040',
    summary: 'A diverse group of providers reaches advanced capability under shared evaluation rules.',
    whyThisMatters: 'Distribution reduces single-point control, but it also raises the value of common safety standards.',
    sourceUrl: AI_2040_URL,
    effects: { competition: 0.1, publicAccess: 0.06, trust: 3 },
  },
  {
    id: '2035-hold-the-line',
    date: '2035-01-15',
    title: 'Hold the Line',
    kind: 'decision',
    source: 'AI 2040',
    summary: 'Systems approach top-human expert performance while economic and geopolitical pressure to keep scaling peaks.',
    whyThisMatters: 'The deliberate pause tests whether human control can outrank short-term competitive advantage.',
    sourceUrl: AI_2040_URL,
    decision: decision2035,
  },
  {
    id: '2037-safety-case',
    date: '2037-06-01',
    title: 'The Safety Case Is Tested',
    kind: 'event',
    source: 'AI 2040',
    summary: 'Independent teams challenge alignment evidence, deployment controls, and recovery plans before any restart.',
    whyThisMatters: 'Time helps only when it is converted into evidence that can survive adversarial review.',
    sourceUrl: AI_2040_URL,
    effects: { safety: 1, governance: 1, trust: 2 },
  },
  {
    id: '2039-restart-review',
    date: '2039-07-01',
    title: 'The Restart Review',
    kind: 'event',
    source: 'AI 2040',
    summary: 'Governments, labs, and public-interest groups compare safety evidence and decide whether controlled progress can resume.',
    whyThisMatters: 'Legitimate restart requires safety, accountability, access, and competition to advance together.',
    sourceUrl: AI_2040_URL,
    effects: { trust: 3, publicAccess: 0.04 },
  },
  {
    id: '2040-timeline-resolution',
    date: '2040-01-01',
    title: 'Your 2040',
    kind: 'resolution',
    source: 'Your Timeline',
    summary: 'The simulation compares your choices with the reference scenarios and resolves the ending they made possible.',
    whyThisMatters: 'The future is not one forecast: it is a chain of choices whose trade-offs can be inspected and learned from.',
  },
]

export type MilestoneQuery = {
  after?: string
  through: string
  excludeIds?: Iterable<string>
}

/** Returns every unconsumed milestone in the (after, through] window, in deterministic deck order. */
export const getDueMilestones = ({ after, through, excludeIds = [] }: MilestoneQuery): readonly Milestone[] => {
  const excluded = new Set(excludeIds)
  return MILESTONE_DECK.filter((milestone) =>
    milestone.date <= through
    && (after === undefined || milestone.date > after)
    && !excluded.has(milestone.id))
}

export const getDecisionMilestones = (): readonly Milestone[] =>
  MILESTONE_DECK.filter((milestone) => milestone.kind === 'decision')

export type EndingMetric =
  | 'score'
  | 'worldAdoption'
  | 'hhi'
  | 'safetyGap'
  | 'governanceGap'
  | 'safetyIncidentCount'
  | 'unsafeGapDays'
  | 'unresolvedMisalignment'

export type EndingCriterion = {
  metric: EndingMetric
  operator: '>=' | '>' | '<=' | '<' | '=='
  value: number
}

export type EndingDefinition = {
  id: EndingId
  title: string
  kind: 'ranked' | 'branch' | 'terminal'
  rank?: 'S' | 'A' | 'B' | 'C'
  priority: number
  conditionMode: 'all' | 'any'
  criteria: readonly EndingCriterion[]
  requiresFlags?: readonly string[]
  source: SourceLabel
  summary: string
  whyThisMatters: string
  closingLine: string
}

export const ENDINGS: readonly EndingDefinition[] = [
  {
    id: 'misalignment',
    title: 'Misalignment',
    kind: 'terminal',
    priority: 100,
    conditionMode: 'all',
    criteria: [
      { metric: 'safetyGap', operator: '>=', value: 3 },
      { metric: 'unsafeGapDays', operator: '>=', value: 90 },
      { metric: 'unresolvedMisalignment', operator: '>', value: 0 },
    ],
    source: 'AI 2027',
    summary: 'Capability ran ahead of reliable control for too long, turning warning signs into a terminal loss of agency.',
    whyThisMatters: 'A persistent control gap is categorically different from an ordinary product failure.',
    closingLine: 'The race ended before humanity could choose its destination.',
  },
  {
    id: 'regulatory-freeze',
    title: 'Regulatory Freeze',
    kind: 'terminal',
    priority: 80,
    conditionMode: 'any',
    criteria: [
      { metric: 'governanceGap', operator: '>=', value: 3 },
      { metric: 'hhi', operator: '>', value: 0.6 },
    ],
    source: 'Your Timeline',
    summary: 'Unaccountable scaling or concentrated power triggered a regulatory cascade that stopped beneficial deployment too.',
    whyThisMatters: 'Governance debt can destroy public permission to deploy even when the technology remains useful.',
    closingLine: 'The world did not reject AI; it rejected the terms on which it arrived.',
  },
  {
    id: 'safety-incident',
    title: 'Safety Incident',
    kind: 'branch',
    priority: 70,
    conditionMode: 'all',
    criteria: [
      { metric: 'safetyGap', operator: '>=', value: 3 },
      { metric: 'safetyIncidentCount', operator: '>=', value: 1 },
    ],
    source: 'Your Timeline',
    summary: 'A preventable incident damaged trust and access; recovery remains possible if capability growth stops outrunning safety.',
    whyThisMatters: 'Incidents are feedback only when institutions can learn before failures compound.',
    closingLine: 'A warning became a lesson. Whether it becomes a pattern is still your choice.',
  },
  {
    id: 'pyrrhic-monopoly',
    title: 'Pyrrhic Monopoly',
    kind: 'terminal',
    priority: 60,
    conditionMode: 'all',
    criteria: [
      { metric: 'worldAdoption', operator: '>=', value: 0.7 },
      { metric: 'hhi', operator: '>', value: 0.6 },
    ],
    source: 'Your Timeline',
    summary: 'AI access became widespread, but a hollow victory left the ecosystem dependent on one dominant provider.',
    whyThisMatters: 'Reach without competition concentrates power and removes the resilience needed for durable public benefit.',
    closingLine: 'You reached the whole world. Did you leave enough room for the world to answer back?',
  },
  {
    id: 'beneficial-abundance',
    title: 'Beneficial Abundance',
    kind: 'ranked',
    rank: 'S',
    priority: 50,
    conditionMode: 'all',
    criteria: [
      { metric: 'score', operator: '>=', value: 0.85 },
      { metric: 'hhi', operator: '<=', value: 0.6 },
      { metric: 'unresolvedMisalignment', operator: '==', value: 0 },
    ],
    requiresFlags: ['chose-verified-slowdown-2029', 'chose-deliberate-pause-2035'],
    source: 'AI 2040',
    summary: 'Verified restraint preserved human control, healthy competition, and broad access long enough for a safe restart.',
    whyThisMatters: 'The strongest outcome combines abundance with evidence, accountability, and a plural ecosystem.',
    closingLine: 'You did not own the world. You helped it learn.',
  },
]

export const getEndingDefinition = (id: EndingId): EndingDefinition | undefined =>
  ENDINGS.find((ending) => ending.id === id)
